POINTS_FOR_WIN = 100
PODIUM_REFERENCE_POINTS = 95
PODIUM_POSITION_DELTA_POINTS = 5
FINISHING_REFERENCE_POINTS = 87
FINISHING_POSITION_DELTA_POINTS = 3
IMPROVEMENT_POINTS_PER_POSITION = 2
RACE_COMPLETION_POINTS = 15
